#!/bin/sh

docker network create word_def_network

docker stop redis_word_def_instance
docker rm redis_word_def_instance
docker run -p 6379:6379 -d -v "/var/lib/redis:/data" --name redis_word_def_instance --net=word_def_network --restart="always" redis:4

docker stop word_def_instance
docker rm word_def_instance
docker run -p 34001:34001 -d --name word_def_instance --net=word_def_network --restart="always" tirinox/word-def:latest
